$NetBSD$

--- toolkit/library/rust/Cargo.toml.orig	Mon Jul 20 22:49:52 2020
+++ toolkit/library/rust/Cargo.toml
@@ -35,6 +35,7 @@ remote_agent = ["gkrust-shared/remote"]
 glean = ["gkrust-shared/glean"]
 glean_with_gecko = ["gkrust-shared/glean_with_gecko"]
 rust_fxa_client = ["gkrust-shared/rust_fxa_client"]
+with_dbus = ["gkrust-shared/with_dbus"]
 
 [dependencies]
 gkrust-shared = { path = "shared" }
