$NetBSD$

--- media/audioipc/client/Cargo.toml.orig	Thu Jun 25 17:04:48 2020
+++ media/audioipc/client/Cargo.toml
@@ -9,7 +9,6 @@ description = "Cubeb Backend for talking to remote cub
 edition = "2018"
 
 [dependencies]
-audio_thread_priority = "0.22"
 audioipc = { path="../audioipc" }
 cubeb-backend = "0.7"
 futures = { version="0.1.18", default-features=false, features=["use_std"] }
