$NetBSD$

--- media/audioipc/audioipc/Cargo.toml.orig	Fri May 29 06:02:42 2020
+++ media/audioipc/audioipc/Cargo.toml
@@ -19,7 +19,6 @@ serde = "1"
 serde_derive = "1"
 tokio = "0.1"
 tokio-io = "0.1"
-audio_thread_priority = "0.22"
 
 [target.'cfg(unix)'.dependencies]
 iovec = "0.1"
