$NetBSD$

--- toolkit/library/rust/shared/Cargo.toml.orig	Mon Jul 20 22:49:52 2020
+++ toolkit/library/rust/shared/Cargo.toml
@@ -41,7 +41,7 @@ storage = { path = "../../../../storage/rust" }
 bookmark_sync = { path = "../../../components/places/bookmark_sync", optional = true }
 shift_or_euc_c = "0.1.0"
 chardetng_c = "0.1.1"
-audio_thread_priority = "0.22.1"
+audio_thread_priority = "0.23.4"
 mdns_service = { path="../../../../media/mtransport/mdns_service", optional = true }
 neqo_glue = { path = "../../../../netwerk/socket/neqo_glue" }
 rlbox_lucet_sandbox = { version = "0.1.0", optional = true }
@@ -103,6 +103,7 @@ remote_agent = ["remote"]
 glean = ["fog"]
 glean_with_gecko = ["fog/with_gecko"]
 rust_fxa_client = ["firefox-accounts-bridge"]
+with_dbus = ["audio_thread_priority/with_dbus"]
 
 [lib]
 path = "lib.rs"
