$NetBSD: patch-Cargo.toml,v 1.4 2020/10/12 12:04:14 pin Exp $

Use portaudio by default

--- Cargo.toml.orig	2020-10-10 19:00:54.000000000 +0000
+++ Cargo.toml
@@ -51,12 +51,6 @@ version = "0.15"
 default-features = false
 
 [features]
-share_clipboard = ["clipboard"]
-alsa_backend = ["librespot-playback/alsa-backend"]
-pulseaudio_backend = ["librespot-playback/pulseaudio-backend"]
-rodio_backend = ["librespot-playback/rodio-backend"]
 portaudio_backend = ["librespot-playback/portaudio-backend"]
-termion_backend = ["cursive/termion-backend"]
-mpris = ["dbus"]
 notify = ["notify-rust"]
-default = ["share_clipboard", "pulseaudio_backend", "mpris", "notify", "cursive/pancurses-backend"]
+default = ["portaudio_backend", "notify", "cursive/pancurses-backend"]
