$NetBSD: patch-Cargo.toml,v 1.1 2020/08/20 16:24:59 pin Exp $

Use portaudio by default

--- Cargo.toml.orig	2020-07-17 22:02:08.000000000 +0000
+++ Cargo.toml
@@ -48,11 +48,5 @@ version = "0.15"
 default-features = false
 
 [features]
-share_clipboard = ["clipboard"]
-alsa_backend = ["librespot-playback/alsa-backend"]
-pulseaudio_backend = ["librespot-playback/pulseaudio-backend"]
-rodio_backend = ["librespot-playback/rodio-backend"]
 portaudio_backend = ["librespot-playback/portaudio-backend"]
-termion_backend = ["cursive/termion-backend"]
-mpris = ["dbus"]
-default = ["share_clipboard", "pulseaudio_backend", "mpris", "cursive/pancurses-backend"]
+default = ["portaudio_backend", "cursive/pancurses-backend"]
