$NetBSD: patch-Cargo.toml,v 1.3 2020/09/04 11:49:46 pin Exp $

Use portaudio by default

--- Cargo.toml.orig	2020-09-01 05:54:45.000000000 +0000
+++ Cargo.toml
@@ -50,11 +50,5 @@ version = "0.15"
 default-features = false
 
 [features]
-share_clipboard = ["clipboard"]
-alsa_backend = ["librespot-playback/alsa-backend"]
-pulseaudio_backend = ["librespot-playback/pulseaudio-backend"]
-rodio_backend = ["librespot-playback/rodio-backend"]
 portaudio_backend = ["librespot-playback/portaudio-backend"]
-termion_backend = ["cursive/termion-backend"]
-mpris = ["dbus"]
-default = ["share_clipboard", "pulseaudio_backend", "mpris", "cursive/pancurses-backend"]
+default = ["portaudio_backend", "cursive/pancurses-backend"]
